title: AEH1707 Blog
author: Abdelhadi Hireche
email: abdelhadi.hireche@outlook.com
description: > # Practicing GitHub Pages

# social links
twitter_username: aeh1707
github_username:  aeh1707

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
